### ISSUE TITLE
Non-existant reward given from Loot Crate

### ISSUE THREAD

**Issue by MGlolenstine** [kreezxil/cobbleblock#12]
From the wood quest I've gotten a Loot crate, which gave me a non-existant item
![image](https://user-images.githubusercontent.com/9406770/51850820-dd4a3900-2322-11e9-80d3-fd6e4ea2a2b0.png)
It could be a problem with the configuration or maybe something else entirely.

**Comment by kreezxil** [comment]
thank you for the report, I'll get this fixed on the next update.

**Comment by kreezxil** [comment]
i'm looking at this and that item exists, are you updated to the latest version?

**Comment by MGlolenstine** [comment]
Currently not at my pc, but I've installed the latest version yesterday, so if there was no updates between, then yeah, I'm using the latest version...

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/51871947-6d857f80-231d-11e9-8405-dfa943b6e217.png)

**Comment by MGlolenstine** [comment]
Really weird... Keep it closed, will take a look tomorrow's afternoon and will report back, will try updating it as well.

**Comment by MGlolenstine** [comment]
Fixed by updating the modpack... For some reason I was still stuck at 1.1 instead of 1.3.4... Sorry for that.
