### ISSUE TITLE
[Recipe Conflict] Between Stone Wand and Building Tool

### ISSUE THREAD

**Issue by badfeet** [kreezxil/cobbleblock#15]
**Describe the bug**
When you attempt to build the Stone Stone Wand (#8191) from Better Builder's Wands you actually get a Building Tool (#7716) from Structurize.  Problem is they have different functions.

**To Reproduce**
craft a stone wand and you get something else

**Versions:**
1.3.4 launched through Twitch

**Comment by badfeet** [comment]
Actually, the issue exists with the iron wand also.  It creates a 'Scan Tool'

**Comment by badfeet** [comment]
![2019-01-31_10 08 34](https://user-images.githubusercontent.com/11754850/52067596-8621af80-2540-11e9-9c11-d703255d906d.png)

Now my base looks like this and I can't find a way to get rid if it!  It is not really there, just some kind of projection or something.

**Comment by kreezxil** [comment]
right click the hologram with the build wand and click the red check mark.

Also look in the output slot, there is a button below it, it'll become active if the recipe has more than one output, press the button to cycle the recipe. And the report the recipes to us here and we'll get those in to the next patch.

You don't have to report this one, we got it. It'll be in the next update, either tonite or tomorrow Texas time. (GMT -6)

**Comment by kreezxil** [comment]
We've fixed this, it'll be in the next update.
