### ISSUE TITLE
[please fix] Cant create Tritium

### ISSUE THREAD

**Issue by purestone9** [kreezxil/cobbleblock#19]
Unable to craft Tritium from Mekanism.
To fix please enable the following in the config for the mod

SolarGeneratorEnabled=true
AdvancedSolarGeneratorEnabled=true
SolarNeutronActivatorEnabled=true

Here is a link to the config with the changes already made
https://pastebin.com/te5yi5GB

if you also want you could say "Let there be wind"
and enable the Wind Generator

**Comment by kreezxil** [comment]
fixed
