### ISSUE TITLE
[please fix] Minecolonies missing

### ISSUE THREAD

**Issue by MGlolenstine** [kreezxil/cobbleblock#21]
**Describe the bug**

**To Reproduce**
1. Open the Quest book

**Screenshots**

![image](https://user-images.githubusercontent.com/9406770/52883054-ed0ead80-3169-11e9-9a47-7a82ef07cae0.png)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: idk
 - Mod Pack: 2.3.12
 - Mod Name:
 - Mod Version:

**Additional context**

**Comment by kreezxil** [comment]
Minecolonies was removed as it does not fit with the pack and this quest has also been removed in 2.4.13.
