### ISSUE TITLE
[please fix] Buildcraft items in Loot Boxes

### ISSUE THREAD

**Issue by MGlolenstine** [kreezxil/cobbleblock#22]
**Describe the bug**

Buildcraft items still drop from Loot Boxes

**To Reproduce**
1. Open a Loot Box and keep doing that until you get a BuildCraft Item

**Screenshots**

![image](https://user-images.githubusercontent.com/9406770/52883130-2e06c200-316a-11e9-825a-09a2e1a555df.png)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: idk
 - Mod Pack : 2.3.12
 - Mod Name:
 - Mod Version:

**Additional context**

**Comment by kreezxil** [comment]
fixed in 2.4.13
