### ISSUE TITLE
[please fix] Chicken quests all complete automatically

### ISSUE THREAD

**Issue by MGlolenstine** [kreezxil/cobbleblock#23]
**Describe the bug**

Chicken quest get completed as soon as any other chicken is put in the inventory

**To Reproduce**
1. Login to the world
2. Complete until you're able to start completing chicken quests
3. Put a normal Roost Chicken in your inventory
4. There you go, all quests completed

**Screenshots**

All of my chickens so far:
![image](https://user-images.githubusercontent.com/9406770/53124304-4d7f5f80-355b-11e9-9f62-985a873b71ae.png)
Quests completed:
![image](https://user-images.githubusercontent.com/9406770/53124315-54a66d80-355b-11e9-82b6-bd881674a892.png)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: idk
 - Mod Pack : 2.5.14
 - Mod Name:
 - Mod Version:

**Additional context**

**Comment by kreezxil** [comment]
this is fixed
