### ISSUE TITLE
Quest Config Empty

### ISSUE THREAD

**Issue by Joelifer123** [kreezxil/cobbleblock#24]
The quest do not seem to exist and when I go into the config folder for ftb quests, The config seems to show that there are no quests, If this is intended then I would suggest removing the ftb quests mod, however I do not believe that is the case

 - Minecraft: 1.12.2
 - Forge: forge-14.23.5.2847
 - Mod Pack : 2.8.17
 - Mod Name:ftb quests
 - Mod Version:1.8.0.237

**Comment by kreezxil** [comment]
that is not intended and when I checked last night before exporting the
quest was there. I will double check in a moment and correct it if it is in
error which I suspect it is.

**Comment by kreezxil** [comment]
I found the issue, the config folder didn't even export. will have an fix in place shortly.
