### ISSUE TITLE
[please fix] suffocating in a wall when entering the mining dimension 

### ISSUE THREAD

**Issue by daodragon** [kreezxil/cobbleblock#7]
When you get teleported to the mining world it doesn't clear out  the area you tp to. meaning you spawn in a wall and suffocate to death.
**To Reproduce**
1. Go to 'mining world'
2. Die

**Versions:**

 - Minecraft:
 - Forge: 2808
 - Mod Pack prebuild e

**Comment by kreezxil** [comment]
we're looking into why this doesn't happen in stoneblock so we can apply the solution

**Comment by kreezxil** [comment]
I've made every effort to ensure the mod responsible for this configured correctly. No one else since this was reported seems to have an issue. It might've just existed before I updated the config. Closing for now.
